#!/bin/bash

yum install -y nodejs
yum install -y npm
yum install -y nano
ln -sv /usr/bin/nano /usr/bin/pico

npm install -g repl.history
npm install -g bower
npm install -g gulp

cd ~
git clone git@github.com:TheWeatherCompany/wxu-drupal.git

ln -s ~/wxu-drupal /dru
